# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Maidens
email: johnmaidens@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  John Maidens is a PhD student in Electrical Engineering and 
  Computer Sciences at the University of California, Berkeley. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maidens.github.io" # the base hostname & protocol for your site
# twitter_username: john_maidens
github_username:  maidens

# Build settings
markdown: kramdown
